### ISSUE TITLE
Building master or develop result in SonarQube error

### ISSUE THREAD

**Issue by delannoyk** [Backelite/sonar-objective-c#1]
Hi,

I've been struggling with the plugin installation.
When I use the `0.4.0.3` from the release page, and copy it in my plugin folder SonarQube still runs although running `run-sonar.sh` doesn't work:

```
Skipping FauxPas (not installed)
Running SonarQube using SonarQube Runner.ERROR: Error during SonarQube Scanner execution
ERROR: Unable to register extension org.sonar.plugins.objectivec.core.ObjectiveCSourceImporter
ERROR: Caused by: org/sonar/api/resources/ProjectFileSystem
ERROR: Caused by: org.sonar.api.resources.ProjectFileSystem
ERROR: 
ERROR: To see the full stack trace of the errors, re-run SonarQube Scanner with the -e switch.
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
ERROR - Command 'sonar-runner ' failed with error code: 1
```

So I also tried building and deploying it myself from the source. I tried sources on the `master` and on the `develop` branch both resulting in breaking SonarQube.
Basically, right after the installation from source (running `./build_and_deploy.sh`) I run `sonar restart` and `sonar status` and I get `SonarQube is not running.`.

Do you have any idea what could go wrong?
I'm using SonarQube 5.3.

**Comment by zippy1978** [comment]
Hi this is fixed with new release 0.5.0.
