### ISSUE TITLE
Failed to execute sonar-maven-plugin:3.2:sonar Unable to register extension org.sonar.plugins.objectivec.ObjectiveCSquidSensor from plugin 'backelitesonarobjectivecplugin': 

### ISSUE THREAD

**Issue by ahmadou** [Backelite/sonar-objective-c#17]
Hi,

I'm experiencing an issue after installing the laste version of the plugin.
My sonar build fails on all my other projects.

Here are my logs and the versions of the plugins and sonar in use.

11:38:34.893 [INFO] --- **sonar-maven-plugin:3.2**:sonar (default-cli) @ import-price ---
11:38:35.812 [INFO] User cache: /root/.sonar/cache
11:38:38.713 [INFO] Load global repositories
11:38:39.087 [INFO] Load global repositories (done) | time=376ms
11:38:39.116 [INFO] User cache: /root/.sonar/cache
11:38:39.595 [INFO] Load plugins index
11:38:39.600 [INFO] Load plugins index (done) | time=5ms
11:38:39.604 [INFO] Download sonar-css-plugin-2.2.jar
11:38:39.868 [INFO] Download sonar-android-plugin-1.1.jar
11:38:40.646 [INFO] Download sonar-json-plugin-2.1.jar
11:38:40.760 [INFO] Download **backelite-sonar-swift-plugin-0.3.0.jar**
11:38:40.902 [INFO] Download sonar-javascript-plugin-2.18.0.3454.jar
11:38:41.082 [INFO] Download sonar-findbugs-plugin-3.4.3.jar
11:38:41.648 [INFO] Download sonar-java-plugin-4.2.1.6971.jar
11:38:42.000 [INFO] Download sonar-web-plugin-2.5.0.476.jar
11:38:42.118 [INFO] Download sonar-ldap-plugin-2.1.0.507.jar
11:38:42.142 [INFO] Download sonar-scm-git-plugin-1.2.jar
11:38:42.328 [INFO] Download sonar-xml-plugin-1.4.1.jar
11:38:42.618 [INFO] Download **backelite-sonar-objective-c-plugin-0.5.2.jar**
11:38:42.824 [INFO] Download sonar-php-plugin-2.9.0.1664.jar
11:38:43.076 [INFO] Download sonar-l10n-fr-plugin-1.13.jar
11:38:43.084 [INFO] Plugin [l10nfr] defines 'l10nen' as base plugin. This metadata can be removed from manifest of l10n plugins since version 5.2.
11:38:43.085 [INFO] Download sonar-generic-coverage-plugin-1.2.jar
11:38:43.796 [INFO] **SonarQube version: 6.0**
11:38:47.446 [INFO] Default locale: "en_US", source code encoding: "UTF-8"
11:38:47.815 [INFO] Process project properties
11:38:47.912 [INFO] Load project repositories
11:38:48.088 [INFO] Load project repositories (done) | time=175ms
11:38:48.172 [INFO] Load quality profiles
11:38:48.326 [INFO] Load quality profiles (done) | time=154ms
11:38:48.336 [INFO] Load active rules
11:38:49.942 [INFO] Load active rules (done) | time=1605ms
11:38:49.996 [INFO] Publish mode
11:38:49.998 [INFO] -------------  Scan import-price xxxxx-import-price_develop
11:38:50.164 [INFO] ------------------------------------------------------------------------
11:38:50.165 [INFO] BUILD FAILURE
11:38:50.165 [INFO] ------------------------------------------------------------------------
11:38:50.165 [INFO] Total time: 17.632 s
11:38:50.165 [INFO] Finished at: 2017-01-11T11:38:50+01:00
11:38:50.534 [INFO] Final Memory: 72M/507M
11:38:50.534 [INFO] ------------------------------------------------------------------------
**11:38:50.536 [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar (default-cli) on project import-price: Unable to register extension org.sonar.plugins.objectivec.ObjectiveCSquidSensor from plugin 'backelitesonarobjectivecplugin': Lorg/sonar/api/checks/AnnotationCheckFactory;: org.sonar.api.checks.AnnotationCheckFactory -> [Help 1]**

**Comment by hoanganhbk94** [comment]
Me too :(

**Comment by MrCloud** [comment]
Up!

**Comment by pbernery** [comment]
You are using SonarQube 6, but the plugin has only been tested on SonarQube 4 and 5. I guess the plugin is not compatible with version 6. 

We are not yet using this version here, so feel free to propose a PR, we will verify and accept it rapidly.

**Comment by zippy1978** [comment]
Hi,

SonarQube 6 to 6.2 is now fully supported with release [0.6.0](https://github.com/Backelite/sonar-objective-c/releases/tag/0.6.0)
