### ISSUE TITLE
xctool with xcode8

### ISSUE THREAD

**Issue by pravinuttarwar** [Backelite/sonar-objective-c#38]
I am getting following error when I try to run project with xcode8,

> Extracting Xcode project information.ERROR: Unexpected action: clean
> ERROR - Command 'xctool -workspace LifeList.xcworkspace -sdk iphonesimulator ARCHS=i386 VALID_ARCHS=i386 CURRENT_ARCH=i386 ONLY_ACTIVE_ARCH=NO -scheme LifeList clean' failed with error code: 4

As xctool is not supported anymore with xcode8, Any thoughts how we can replace xctool with any other build tool?

**Comment by pbernery** [comment]
You can use `xcodebuild` directly. `xctool` is indeed not supported anymore, `xcodebuild` is now mature enough to run unit tests.
