### ISSUE TITLE
can soanr-objective-c support 6.5?

### ISSUE THREAD

**Issue by RogerAbyss** [Backelite/sonar-objective-c#43]
I use docker file to build sonarqube, it is 6.5.but seems sonar-objective-c 0.6.1 do not support yet.

**Comment by JackLeo** [comment]
AFAIK this is duplicate of https://github.com/Backelite/sonar-objective-c/issues/39

**Comment by andrewclaus** [comment]
I was able to get the plugin working with Sonar 6.5 the change in my pull request here: https://github.com/Backelite/sonar-objective-c/pull/48

**Comment by zippy1978** [comment]
Hi all,

Version 0.6.2 of the plugin now works with SonarQube 6.5.

Regards,
Gilles
