### ISSUE TITLE
N Code Smells BUT 0 Bugs 0 Vulnerabilities reported, another plugin for Objective-C ?

### ISSUE THREAD

**Issue by egr-ext** [Backelite/sonar-objective-c#66]
Good morning,

I'am able to make this sonar-objective-c plugin reporting well the "Code Smells" but it does not report any "Bugs" neither "Vulnerabilities".
Is there another open source free plugin that would report the bugs in Sonar for objective-c language ?

Many thanks

**Comment by raatiniemi** [comment]
This seem to be caused by the fact that neither OCLint nor FauxPas have their rules classified, i.e. each rule use the default type (which is code smell).

From what I know, this is the only open source free plugin available, however there are a few forks with additional changes.

**Comment by egr-ext** [comment]
Ok thanks for the info
