### ISSUE TITLE
Error during SonarQube Scanner execution. The rule 'OCLint:compiler error' does not exist.

### ISSUE THREAD

**Issue by sadaf-behbahani** [Backelite/sonar-objective-c#72]
Hello, I am facing two errors when uploading the results on my sonar server where I have objective c plugin installed. 

1- The rule 'OCLint:compiler error' does not exist.
2- The rule 'OCLint:compiler warning' does not exist.

OCLint version: 0.13.
sonar-objective-c version: 0.6.3

I checked in the plugin they were not listed in 'profile-oclint.xml' and 'rules.txt'. I added them manually so now it works . 
I saw there are similars issues related to this problem and they are still open. I also saw there is commit which solves the problem for OCLint:compiler warning but it is not merged. 

Do you know when these rules are going to be merged ? 

Thanks

**Comment by zippy1978** [comment]
Hi @sadaf-behbahani ,

This plugin (sonar-objective-c) is not maintained anymore : you can now use the swift plugin for ObjC and : Swift https://github.com/Backelite/sonar-swift.

Release 0.4.2 of the sonar-swift-plugin fixes the issue you mention

Gilles
