### ISSUE TITLE
Not support SonarQube 6.0

### ISSUE THREAD

**Issue by GeorgeChan** [Backelite/sonar-objective-c#9]
v0.5.2 can't support SonarQube 6.0.

**Comment by zippy1978** [comment]
Hi,

Yes I know, I will have a look at it.

Gilles

**Comment by aanjanhari** [comment]
sir, any updates on this.

**Comment by azizur** [comment]
Any update on this?

**Comment by zippy1978** [comment]
Same as https://github.com/Backelite/sonar-objective-c/issues/14.

I close it.
